EC-350 Send comment for review
nice-digital/consultations pull request #317
Opened 2020-12-17 17:12 UTC by suegarner

https://nicedigital.atlassian.net/browse/EC-350

2021-02-12 16:15 UTC, John-Williams requested changes
i've added a few comments / questions. as always, they're up for debate.

thanks.

2021-02-12 16:15 UTC, John-Williams commented on Comments/ClientApp/src/components/SubmitResponseFeedback/SubmitResponseFeedback.js
> +	const emailRegex = /\S+@\S+\.\S+/;
is this really necessary here too?

2021-02-12 17:53 UTC, johnholland-nice commented on Comments/ClientApp/src/components/Review/Review.js
> +				this.setState({
Yes; I wasn't sure whether they would still be applicable or if we would need more. I will investigate.

2021-02-17 15:45 UTC, John-Williams requested changes

2021-02-17 15:45 UTC, John-Williams commented on Comments/Services/SubmitService.cs
> +			var earliestDate = submissionToSave.SubmissionComment.Any() ? submissionToSave.SubmissionComment.Min(sc => sc.Comment.CreatedDate) : DateTime.MaxValue;
is there any chance this block of code could be shared between the submissions please?

It's just quite a chunk of code that looks identical to me.

so it'd be something like:

Submission.DurationBetweenFirstCommentOrAnswerSavedAndSubmissionInSeconds = GetDuration(submissionToSave);

then all that code could be moved into a GetDuration function.

2021-02-17 16:19 UTC, John-Williams approved these changes
thanks both!

2021-02-18 16:38 UTC, merged