EC-873 Show tally of submissions to Commenting lead
nice-digital/consultations pull request #341
Opened 2021-03-19 10:59 UTC by suegarner

https://nicedigital.atlassian.net/browse/EC-873

2021-04-07 13:48 UTC, John-Williams requested changes

2021-04-07 13:48 UTC, John-Williams commented on Comments/Models/Context.cs
> +            var commentsCount = comments.Where(c => c.OrganisationUser?.OrganisationAuthorisation != null)
do you think the count could be returned straight from the database please? 

same with the answers line 1040.

2021-04-07 13:48 UTC, John-Williams commented on Comments.Test/UnitTests/ConsultationContext.Tests.cs
> +		}
could CountCommentsAndAnswerSubmissionsForThisOrganisation be tested as well please?

2021-04-13 10:06 UTC, emollett submitted a review, later dismissed

2021-04-14 13:18 UTC, mgallagher1980 approved these changes

2021-04-14 13:18 UTC, mgallagher1980 submitted a review, later dismissed

2021-04-15 12:51 UTC, mgallagher1980 approved these changes

2021-04-15 12:58 UTC, merged